[package]
name = "config"
edition.workspace = true
version.workspace = true

[dependencies]
tracing = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
model = { workspace = true }

[lints]
workspace = true
